### ISSUE TITLE
Private repo w/tag in workflow

### ISSUE THREAD

**Issue by stoked10** [actions/runner#1718]
**Description:** 
We want to use a workflow action to lint and test our code on push, We use three private repos with oauth keys in our package.json.

**Bug:**
Each private repo reference in our package.json references a tag for that repo. The work flow fails with "Repository not found". For example:

package.json dependency:
`"Private-Repo1": "https://<PAT>:x-oauth-basic@github.com/project/Private-Repo.git#v1.0.0",`

The oauth key is set to allow checking out the repo as well as workflow access. When attempting to run the work flow we get:

```
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ***github.com/project/Private-Repo.git
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/project/Private-Repo.git/' not found
```
our yaml:
```
name: API auto test and lint workflow

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: git config --global url."https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"
    - run: npm ci
    - run: npm run lint
    - run: npm run test
```
(I know the replace is redundant, we tried everything we could find)

Local testing is pointing to the reason that we’re failing is that `git ls-remote` fails when you point to a private repo with a tag number, if I remove the tag it works.

**To Reproduce**
1. Create a prviate repo and tag a version
2. Create an oauth key, give it git and workflow access
3. Create a secret named GIT_TOKEN that is your key
4. Add the private repo with oauth key to your repo package.json
5. Create a workflow for your repo with the above YAML
6. Run the workflow

**Expected behavior**
To be able to reference a private repo w/tag in our package.json that also works in a workflow

**Comment by nikola-jokic** [comment]
Hi @stoked10,

While reading this issue, it seems like the error was thrown while executing npm. Did you try executing npm run lint with a tagged version without the runner itself? The runner application will execute npm run lint, with the checked-out code you provide. The execution falls to the npm installed with your previous step. The runner will execute npm command found on the path and the execution itself would be up to the npm.

It seems to me that the npm could not fetch the repository based on the package.json. Could you please confirm that you can run npm run lint in your environment without the runner, with the tag specified as per package.json docs?

**Comment by stoked10** [comment]
Thanks for the response @nikola-jokic 

lint does work locally with a tagged private repo. 

Getting down to where I'm at:

Errors with repo not found: `git ls-remote https://<PAT>:x-oauth-basic@github.com/project/Private-Repo.git#v1.0.0`
Successfully ls's the repo: `git ls-remote https://<PAT>:x-oauth-basic@github.com/project/Private-Repo.git`

Locally I get the same error from the tagged version ls-remote as I get above.

**Comment by nikola-jokic** [comment]
Hey @stoked10,

This is not really a runner issue so I will close it now. As I pointed out, and you have tested, git ls-remote fails even without the runner, and it seems like npm is invoking it when you are trying to run your action.

As I explained, the runner is invoking npm which takes your checked-out repository and runs commands. You can replicate each command on your own machine and find the root cause of your issue 😊

**Comment by stoked10** [comment]
Okay. I'm confident that `git ls-remote` is my root cause. Is there anyway to override the runner from using it?

**Comment by nikola-jokic** [comment]
I don't believe so. The runner will execute steps provided by the yaml. The yaml specifies that you should checkout your project, setup node and execute `npm ...`. It is practically doing what is told to do, and the execution of the command is causing your problem.

You can make it work only by specifying what you would do when you build your project. If it works fine there, it should be working fine on the runner, since it automated steps that you define to be taken automatically on some event. If the runner is failing, but the steps are ok, then it is a bug we will investigate to reproduce it.

In your specific usecase, I believe that the issue falls to the npm execution, and I have found similar issues on stack overflow.

I believe that if you set that the way npm would accept it, the runner would not cause any problem and will complete execution as you would manually do.

If that is not the case if manually executing exactly what the runner executes works, and the runner fails, feel free to re-open this issue. We are happy to fix those bugs! But I believe that, when you set this up to work locally, it will work on the runner as well

**Comment by bmcalees** [comment]
> Okay. I'm confident that `git ls-remote` is my root cause. Is there anyway to override the runner from using it?

@stoked10 Did you ever find a solution for this? I'm running into the same exact issue and all my googling has led me here. Removing the repo tag didn't fix the issue so I'm guessing it's something with permissions?
